### ISSUE TITLE
Run the app on OneDrive

### ISSUE THREAD

**Issue by nguyencamha97** [abrcheng/SharePointOnlineQuickAssist#10]
I want to use the Recycle Bin search feature on my OneDrive bin.
I've successfully added it to OneDrive site contents. Is there any way to run it on OneDrive?
Many thanks

**Comment by JarvenZhang** [comment]
@nguyencamha97 , please follow these steps:  https://github.com/abrcheng/SharePointOnlineQuickAssist/blob/main/Documents/Add%20SPOQA%20to%20OneDrive%20Host%20Site/Add%20SPOQA%20to%20OneDrive%20Host%20Site.md
