### ISSUE TITLE
SharePointOnlineQuickAssist/Packages/spoqa.sppkg haven't been updated in the new release 1.22.04.12

### ISSUE THREAD

**Issue by abrcheng** [abrcheng/SharePointOnlineQuickAssist#2]
SharePointOnlineQuickAssist/Packages/spoqa.sppkg haven't been updated in the new release 1.22.04.12
![image](https://user-images.githubusercontent.com/21354416/162907791-973ce80d-2456-47bc-a183-f478d01134bf.png)

and the home page https://github.com/abrcheng/SharePointOnlineQuickAssist haven't been updated either,
![image](https://user-images.githubusercontent.com/21354416/162907997-64bb5b59-66f9-4cd7-b6b8-a4ee75657592.png)

**Comment by mslukai** [comment]
Replaced latest package and updated home page.
