### ISSUE TITLE
Identifying System Account deleted documents in Restore Items

### ISSUE THREAD

**Issue by MrChrisElliott** [abrcheng/SharePointOnlineQuickAssist#7]
Hi - It would be really helpful if we could identify the items in Recycle Bin that have deleted by the System Account. This is the account that carries out Retention Policy actions. As such this account so does not come with a standard user email to hook items back out of the bin with. As far as I can see the alternative of 'Deleted by Name' would work but perhaps there is another UID that could be revealed. 

Thanks very much.

**Comment by JarvenZhang** [comment]
Hi @MrChrisElliott  For items that deleted by "system account" (such as SHAREPOINT\system or NT AUTHORITY\SYSTEM)

you can use "app@sharepoint" as the deleted by user to search:

<img width="448" alt="image" src="https://user-images.githubusercontent.com/89838160/202062185-9e253035-64b5-479c-81f9-d683b3f188ae.png">



https://learn.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#common-schema

**Comment by JarvenZhang** [comment]
Currently, I dont have any sample file. 

<img width="500" alt="image" src="https://user-images.githubusercontent.com/89838160/202062350-5f57081f-dcb2-40c5-8667-e58ec85eddcf.png">

**Comment by MrChrisElliott** [comment]
Thanks for that suggestion. Much appreciated. Unfortunately, I have just tried the select the System Account deleted files using the ***@***.*** identifier and it did not select any deleted files.

Should I be doing a substitution of "sharepoint" for our domain name ***@***.*** ? Is there anything else I shoild be looking at?

Chris Elliott
M: 07828557022
https://www.linkedin.com/in/chris-elliott-9b47794/

________________________________

**Comment by JarvenZhang** [comment]
Hi @MrChrisElliott , Yes, I found a site where have files deleted by "System Account".

It looks "app@sharepoint" also doesn't help here, I will check the fix the code.

**Comment by MrChrisElliott** [comment]
Thanks. That is much appreciated.

Regards,
Chris Elliott
07828557022

On 17 Nov 2022, at 02:04, Jarven ***@***.***> wrote:

﻿

Hi @MrChrisElliott<https://github.com/MrChrisElliott> , Yes, I found a site where have files deleted by "System Account".

It looks ***@***.***" also doesn't help here, I will check the fix the code.

**Comment by JarvenZhang** [comment]
Code checked in with PR

**Comment by MrChrisElliott** [comment]
Hi - I just need to check with you. Are the changes now fixed and available in the release on the app store? (or doesn't it work like that anymore).

Chris Elliott

________________________________

**Comment by JarvenZhang** [comment]
Hi Chris

No, the update doesn't apply to AppStore yet.

You can manually replace the package from github or attachment.

Below are steps:
https://github.com/abrcheng/SharePointOnlineQuickAssist/tree/main/Packages#deploy-the-tool-tenant-level-app-catalog


BR
Jarven
